apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: user
  namespace: default
  labels:
    serving.knative.dev/visibility: cluster-local
spec:
  template:
    metadata:
      name: user-service-v2
      annotations:
        autoscaling.knative.dev/minScale: "1"
    spec:
      containers:
        - image: registry.cn-shanghai.aliyuncs.com/jike-serverless/user
          ports:
            - name: http1
              containerPort: 3002
          env:
            - name: version
              value: 'v2'
      imagePullSecrets:
          - name: regcred
  traffic:
    - tag: v1
      revisionName: user-service-v1
      percent: 50
    - tag: v2
      revisionName: user-service-v2
      percent: 50
    - tag: latest
      latestRevision: true
      percent: 0
