apiVersion: v1
kind: Service
metadata:
  name: user
spec:
  type: ClusterIP
  selector:
    app: user
  ports:
    - name: http
      protocol: TCP
      port: 3002
      targetPort: 3002
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2，after 1.9.0 use apps/v1
kind: Deployment
metadata:
  name: user
spec:
  selector:
    matchLabels:
      app: user
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
        - image: registry.cn-shanghai.aliyuncs.com/jike-serverless/user
          name: user
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          ports:
            - containerPort: 3002
              name: user
      imagePullSecrets:
        - name: regcred

#apiVersion: v1
#kind: Pod
#metadata:
#  name: myapp
#spec:
#  containers:
#    - name: myapp
#      image: registry.cn-shanghai.aliyuncs.com/jike-serverless/todolist:latest
#  imagePullSecrets:
#    - name: regcred
